using LogisticsERP.Application.Authorization;

namespace LogisticsERP.Infrastructure.Persistence.SeedData;

internal sealed record PermissionSeed(
    Guid Id,
    string Key,
    string Category,
    string NameAr,
    string NameEn,
    string DescriptionAr,
    string DescriptionEn,
    bool RequiresHousingScope,
    bool RequiresClientScope,
    bool IsSensitive,
    bool IsHighTrust,
    string? GrantabilityRule,
    int DisplayOrder);

internal static class PermissionSeedCatalog
{
    public static IReadOnlyList<PermissionSeed> All { get; } =
    [
        Create(1, PermissionKeys.Security.UsersRead, "Security", "عرض المستخدمين", "Read users", "عرض حسابات المستخدمين وحالتها.", "View user accounts and their status.", sensitive: true),
        Create(2, PermissionKeys.Security.UsersCreate, "Security", "إنشاء المستخدمين", "Create users", "إنشاء حسابات مستخدمين جديدة.", "Create new user accounts.", sensitive: true, highTrust: true),
        Create(3, PermissionKeys.Security.UsersUpdate, "Security", "تعديل المستخدمين", "Update users", "تعديل حالة وبيانات حسابات المستخدمين.", "Update user account details and status.", sensitive: true, highTrust: true),
        Create(4, PermissionKeys.Security.UsersArchive, "Security", "أرشفة المستخدمين", "Archive users", "أرشفة حساب مستخدم وإبطال جلساته دون حذف بياناته.", "Archive a user and revoke sessions without deleting records.", sensitive: true, highTrust: true),
        Create(5, PermissionKeys.Security.RolesRead, "Security", "عرض الأدوار", "Read roles", "عرض الأدوار وقوالب الصلاحيات.", "View roles and permission templates."),
        Create(6, PermissionKeys.Security.RolesCreate, "Security", "إنشاء الأدوار", "Create roles", "إنشاء الأدوار ضمن النطاق المصرح به.", "Create roles within the authorized scope.", highTrust: true),
        Create(7, PermissionKeys.Security.PermissionsRead, "Security", "عرض الصلاحيات", "Read permissions", "عرض كتالوج الصلاحيات والمنح والمنع.", "View the permission catalog, grants, and denies."),
        Create(8, PermissionKeys.Security.PermissionsCreate, "Security", "إنشاء الصلاحيات", "Create permissions", "إنشاء الصلاحيات ضمن النطاق المصرح به.", "Create permissions within the authorized scope.", highTrust: true),
        Create(9, PermissionKeys.Security.AuditRead, "Security", "عرض سجل التدقيق", "Read audit log", "عرض سجل التدقيق الأمني والتشغيلي.", "View security and operational audit records.", sensitive: true, highTrust: true),
        Create(10, PermissionKeys.Security.SupportAccessCreate, "Security", "إنشاء وصول الدعم", "Create support access", "إنشاء وصول الدعم ضمن النطاق المصرح به.", "Create support access within the authorized scope.", sensitive: true, highTrust: true),

        Create(11, PermissionKeys.Catalog.OperatingCitiesRead, "Catalog", "عرض المدن التشغيلية", "Read operating cities", "عرض المدن والفروع التشغيلية.", "View operating cities and branches."),
        Create(12, PermissionKeys.Catalog.OperatingCitiesCreate, "Catalog", "إنشاء المدن التشغيلية", "Create operating cities", "إنشاء المدن التشغيلية ضمن النطاق المصرح به.", "Create operating cities within the authorized scope."),

        Create(13, PermissionKeys.Workforce.EmployeesRead, "Workforce", "عرض الموظفين", "Read employees", "عرض بيانات الموظفين غير الحساسة.", "View non-sensitive employee data."),
        Create(14, PermissionKeys.Workforce.EmployeesCreate, "Workforce", "إنشاء الموظفين", "Create employees", "إنشاء سجلات موظفين جديدة.", "Create new employee records."),
        Create(15, PermissionKeys.Workforce.EmployeesUpdate, "Workforce", "تعديل الموظفين", "Update employees", "تعديل بيانات الموظفين التشغيلية.", "Update operational employee data."),
        Create(16, PermissionKeys.Workforce.EmployeesArchive, "Workforce", "أرشفة الموظفين", "Archive employees", "أرشفة الموظفين دون حذف تاريخهم.", "Archive employees without deleting their history.", highTrust: true),
        Create(17, PermissionKeys.Workforce.EmployeesSensitiveRead, "Workforce", "عرض بيانات الموظفين الحساسة", "Read sensitive employee data", "عرض الهوية والإقامة والبيانات الشخصية المقيدة.", "View restricted identity, residency, and personal data.", sensitive: true, highTrust: true),
        Create(18, PermissionKeys.Workforce.RidersRead, "Workforce", "عرض المناديب", "Read riders", "عرض ملفات المناديب وبياناتهم التشغيلية.", "View rider profiles and operational data."),
        Create(19, PermissionKeys.Workforce.RidersCreate, "Workforce", "إنشاء المناديب", "Create riders", "إنشاء المناديب ضمن النطاق المصرح به.", "Create riders within the authorized scope."),
        Create(120, PermissionKeys.Workforce.ExternalRidersRead, "Workforce", "عرض المناديب الخارجيين", "Read external riders", "عرض ملفات المناديب الخارجيين.", "View external rider profiles."),
        Create(121, PermissionKeys.Workforce.ExternalRidersCreate, "Workforce", "إنشاء المناديب الخارجيين", "Create external riders", "إنشاء ملفات المناديب الخارجيين.", "Create external rider profiles."),
        Create(122, PermissionKeys.Workforce.ExternalRidersUpdate, "Workforce", "تعديل المناديب الخارجيين", "Edit external riders", "تعديل ملفات المناديب الخارجيين.", "Update external rider profiles."),
        Create(123, PermissionKeys.Workforce.ExternalRidersDelete, "Workforce", "حذف المناديب الخارجيين", "Delete external riders", "أرشفة ملفات المناديب الخارجيين مع حفظ التاريخ.", "Archive external rider profiles while retaining history."),
        Create(20, PermissionKeys.Workforce.SponsorsRead, "Workforce", "عرض الكفلاء", "Read sponsors", "عرض جهات الكفالة وبيانات السجل.", "View sponsors and registry information.", sensitive: true),
        Create(21, PermissionKeys.Workforce.SponsorsCreate, "Workforce", "إنشاء الكفلاء", "Create sponsors", "إنشاء الكفلاء ضمن النطاق المصرح به.", "Create sponsors within the authorized scope.", sensitive: true),

        Create(22, PermissionKeys.Compliance.ResidencyRead, "Compliance", "عرض الإقامات", "Read residency permits", "عرض بيانات الإقامة المقيدة.", "View restricted residency permit data.", sensitive: true),
        Create(23, PermissionKeys.Compliance.ResidencyCreate, "Compliance", "إنشاء الإقامات", "Create residency permits", "إنشاء الإقامات ضمن النطاق المصرح به.", "Create residency permits within the authorized scope.", sensitive: true),
        Create(24, PermissionKeys.Compliance.LicensesRead, "Compliance", "عرض الرخص", "Read driver licenses", "عرض رخص القيادة وإصداراتها.", "View driver licenses and their versions.", sensitive: true),
        Create(25, PermissionKeys.Compliance.LicensesCreate, "Compliance", "إنشاء الرخص", "Create driver licenses", "إنشاء الرخص ضمن النطاق المصرح به.", "Create driver licenses within the authorized scope.", sensitive: true),
        Create(26, PermissionKeys.Compliance.RiderCardsRead, "Compliance", "عرض بطاقات السائق", "Read rider cards", "عرض بطاقات السائق وتجديداتها.", "View rider cards and renewals.", sensitive: true),
        Create(27, PermissionKeys.Compliance.RiderCardsCreate, "Compliance", "إنشاء بطاقات السائق", "Create rider cards", "إنشاء بطاقات السائق ضمن النطاق المصرح به.", "Create rider cards within the authorized scope.", sensitive: true),
        Create(28, PermissionKeys.Compliance.HealthCardsRead, "Compliance", "عرض البطاقات الصحية", "Read health cards", "عرض البطاقات الصحية وتجديداتها.", "View health cards and renewals.", sensitive: true),
        Create(29, PermissionKeys.Compliance.HealthCardsCreate, "Compliance", "إنشاء البطاقات الصحية", "Create health cards", "إنشاء البطاقات الصحية ضمن النطاق المصرح به.", "Create health cards within the authorized scope.", sensitive: true),
        Create(30, PermissionKeys.Compliance.InsuranceRead, "Compliance", "عرض التأمين الطبي", "Read medical insurance", "عرض وثائق ومستويات التأمين الطبي.", "View medical-insurance policies and plan levels.", sensitive: true),
        Create(31, PermissionKeys.Compliance.InsuranceCreate, "Compliance", "إنشاء التأمين الطبي", "Create medical insurance", "إنشاء التأمين الطبي ضمن النطاق المصرح به.", "Create medical insurance within the authorized scope.", sensitive: true),
        Create(32, PermissionKeys.Compliance.PromissoryNotesRead, "Compliance", "عرض سندات الأمر", "Read promissory notes", "عرض بيانات سندات الأمر المالية.", "View financial promissory-note data.", sensitive: true, highTrust: true),
        Create(33, PermissionKeys.Compliance.PromissoryNotesCreate, "Compliance", "إنشاء سندات الأمر", "Create promissory notes", "إنشاء سندات الأمر ضمن النطاق المصرح به.", "Create promissory notes within the authorized scope.", sensitive: true, highTrust: true),

        Create(34, PermissionKeys.Documents.Read, "Documents", "عرض بيانات الوثائق", "Read document metadata", "عرض بيانات الوثائق ونسخها دون تنزيل المحتوى.", "View document metadata and versions without downloading content.", sensitive: true),
        Create(35, PermissionKeys.Documents.Upload, "Documents", "رفع الوثائق", "Upload documents", "رفع نسخة وثيقة جديدة وفق سياسة الملفات.", "Upload a new document version under the file policy.", sensitive: true),
        Create(36, PermissionKeys.Documents.Download, "Documents", "تنزيل الوثائق", "Download documents", "تنزيل محتوى الوثائق غير المصنفة عالية الحساسية.", "Download document content not classified as highly sensitive.", sensitive: true),
        Create(37, PermissionKeys.Documents.DownloadSensitive, "Documents", "تنزيل الوثائق الحساسة", "Download sensitive documents", "تنزيل محتوى وثائق الهوية والمالية عالية الحساسية.", "Download highly sensitive identity and financial documents.", sensitive: true, highTrust: true),

        Create(38, PermissionKeys.Operations.PlatformAccountsRead, "Operations", "عرض حسابات المنصات", "Read platform accounts", "عرض حسابات منصات العملاء ضمن النطاق المسموح.", "View client-platform accounts within the allowed scope.", clientScope: true),
        Create(39, PermissionKeys.Operations.PlatformAccountsCreate, "Operations", "إنشاء حسابات المنصات", "Create platform accounts", "إنشاء حسابات المنصات ضمن النطاق المصرح به.", "Create platform accounts within the authorized scope.", clientScope: true),
        Create(40, PermissionKeys.Operations.PlatformAssignmentsRead, "Operations", "عرض تكليفات المنصات", "Read platform assignments", "عرض تاريخ الاستخدام الفعلي لحسابات المنصات ضمن النطاق.", "View actual platform-account usage history within scope.", clientScope: true),
        Create(41, PermissionKeys.Operations.PlatformAssignmentsCreate, "Operations", "إنشاء تكليفات المنصات", "Create platform assignments", "إنشاء تكليفات المنصات ضمن النطاق المصرح به.", "Create platform assignments within the authorized scope.", clientScope: true),
        Create(42, PermissionKeys.Operations.HousingRead, "Operations", "عرض السكن", "Read housing", "عرض السكن وفترات الإقامة.", "View housing and residence periods."),
        Create(43, PermissionKeys.Operations.HousingCreate, "Operations", "إنشاء السكن", "Create housing", "إنشاء السكن ضمن النطاق المصرح به.", "Create housing within the authorized scope."),

        Create(44, PermissionKeys.Reporting.ReportsRead, "Reporting", "عرض التقارير", "Read reports", "عرض التقارير التشغيلية المصرح بها.", "View authorized operational reports."),
        Create(45, PermissionKeys.Reporting.ExportsCreate, "Reporting", "إنشاء التصديرات", "Create exports", "إنشاء ملفات تصدير من البيانات المصرح بها فقط.", "Create export files from authorized data only.", sensitive: true),
        Create(46, PermissionKeys.Reporting.NotificationsRead, "Reporting", "عرض الإشعارات", "Read notifications", "عرض الإشعارات التشغيلية.", "View operational notifications."),
        Create(47, PermissionKeys.Reporting.NotificationsCreate, "Reporting", "إنشاء الإشعارات", "Create notifications", "إنشاء الإشعارات ضمن النطاق المصرح به.", "Create notifications within the authorized scope."),

        Create(48, PermissionKeys.Workflows.LeaveRequestsRead, "Workflows", "عرض طلبات الإجازة", "Read leave requests", "عرض طلبات الإجازة وتاريخها.", "View leave requests and history.", sensitive: true),
        Create(49, PermissionKeys.Workflows.LeaveRequestsCreate, "Workflows", "إنشاء طلبات الإجازة", "Create leave requests", "إنشاء طلبات الإجازة ضمن النطاق المصرح به.", "Create leave requests within the authorized scope.", sensitive: true),
        Create(50, PermissionKeys.Workflows.LeaveRequestsApprove, "Workflows", "اعتماد طلبات الإجازة", "Approve leave requests", "الموافقة أو الرفض الموثق لطلبات الإجازة.", "Record approval or rejection decisions for leave requests.", sensitive: true, highTrust: true),
        Create(51, PermissionKeys.Workflows.AbsenceCasesRead, "Workflows", "عرض حالات الغياب", "Read absence cases", "عرض حالات الغياب والهروب وسجل أحداثها.", "View absence and escaped-employee cases and their events.", sensitive: true),
        Create(52, PermissionKeys.Workflows.AbsenceCasesCreate, "Workflows", "إنشاء حالات الغياب", "Create absence cases", "إنشاء حالات الغياب ضمن النطاق المصرح به.", "Create absence cases within the authorized scope.", sensitive: true),
        Create(53, PermissionKeys.Workflows.EmployeeStatusChangesRead, "Workflows", "عرض طلبات تغيير الحالة", "Read employee status changes", "عرض طلبات تغيير حالة الموظف.", "View employee status-change requests.", sensitive: true),
        Create(54, PermissionKeys.Workflows.EmployeeStatusChangesCreate, "Workflows", "إنشاء طلبات تغيير الحالة", "Create employee status changes", "إنشاء طلبات تغيير الحالة ضمن النطاق المصرح به.", "Create employee status changes within the authorized scope.", sensitive: true),
        Create(55, PermissionKeys.Workflows.EmployeeStatusChangesApprove, "Workflows", "اعتماد تغيير حالة الموظف", "Approve employee status changes", "اعتماد تغيير حالة الموظف مع حفظ الأثر التاريخي.", "Approve employee status changes while preserving history.", sensitive: true, highTrust: true),

        Create(56, PermissionKeys.Fleet.VehiclesRead, "Fleet", "عرض المركبات", "Read vehicles", "عرض المركبات وهويتها وحالتها.", "View vehicle identity and operational status."),
        Create(57, PermissionKeys.Fleet.VehiclesCreate, "Fleet", "إنشاء المركبات", "Create vehicles", "إنشاء المركبات ضمن النطاق المصرح به.", "Create vehicles within the authorized scope."),
        Create(58, PermissionKeys.Fleet.VehiclesArchive, "Fleet", "أرشفة المركبات", "Archive vehicles", "أرشفة واستعادة المركبات غير المستخدمة.", "Archive and restore unused vehicles.", highTrust: true),
        Create(59, PermissionKeys.Fleet.VehiclesDecommission, "Fleet", "إنهاء خدمة المركبات", "Decommission vehicles", "إنهاء خدمة مركبة بشكل تشغيلي نهائي.", "Operationally decommission a vehicle.", highTrust: true),
        Create(60, PermissionKeys.Fleet.AssignmentsRead, "Fleet", "عرض عهد المركبات", "Read vehicle assignments", "عرض العهد الحالية والتاريخية بين الرايدرز والمركبات.", "View current and historical rider-vehicle assignments."),
        Create(61, PermissionKeys.Fleet.AssignmentsCreate, "Fleet", "إنشاء عهد المركبات", "Create vehicle assignments", "إنشاء عهد المركبات ضمن النطاق المصرح به.", "Create vehicle assignments within the authorized scope."),
        Create(62, PermissionKeys.Fleet.AssignmentsCorrect, "Fleet", "تصحيح عهد المركبات", "Correct vehicle assignments", "تصحيح العهد التاريخية مع سبب إلزامي.", "Correct historical assignments with a mandatory reason.", sensitive: true, highTrust: true),
        Create(63, PermissionKeys.Fleet.IssuesRead, "Fleet", "عرض بلاغات المركبات", "Read vehicle issues", "عرض بلاغات وأعطال المركبات.", "View vehicle issues and faults."),
        Create(64, PermissionKeys.Fleet.IssuesCreate, "Fleet", "إنشاء بلاغات المركبات", "Create vehicle issues", "إنشاء بلاغات المركبات ضمن النطاق المصرح به.", "Create vehicle issues within the authorized scope."),
        Create(65, PermissionKeys.Fleet.ComplianceRead, "Fleet", "عرض التزام المركبات", "Read vehicle compliance", "عرض التسجيل والتأمين والفحص الدوري.", "View vehicle registration, insurance, and inspection."),
        Create(66, PermissionKeys.Fleet.ComplianceCreate, "Fleet", "إنشاء التزام المركبات", "Create vehicle compliance", "إنشاء التزام المركبات ضمن النطاق المصرح به.", "Create vehicle compliance within the authorized scope."),
        Create(67, PermissionKeys.Fleet.FilesRead, "Fleet", "عرض ملفات المركبات", "Read vehicle files", "عرض بيانات ونسخ ملفات المركبات.", "View vehicle file metadata and versions.", sensitive: true),
        Create(68, PermissionKeys.Fleet.FilesUpload, "Fleet", "رفع ملفات المركبات", "Upload vehicle files", "رفع نسخ ملفات المركبات الثابتة.", "Upload fixed vehicle file versions.", sensitive: true),
        Create(69, PermissionKeys.Fleet.FilesDownload, "Fleet", "تنزيل ملفات المركبات", "Download vehicle files", "تنزيل محتوى ملفات المركبات الخاصة.", "Download private vehicle file content.", sensitive: true),
        Create(70, PermissionKeys.Fleet.AccidentsRead, "Fleet", "عرض حوادث المركبات", "Read vehicle accidents", "عرض بيانات الحوادث والأدلة.", "View vehicle accidents and evidence.", sensitive: true),
        Create(71, PermissionKeys.Fleet.AccidentsReport, "Fleet", "تسجيل حوادث المركبات", "Report vehicle accidents", "تسجيل حادث مرتبط برايدر وعهدة فعالة.", "Report an accident linked to a rider and active assignment.", sensitive: true),
        Create(72, PermissionKeys.Fleet.AccidentsFinalize, "Fleet", "اعتماد تقارير الحوادث", "Finalize accident reports", "اعتماد وتصحيح وإغلاق تقارير الحوادث.", "Finalize, correct, and close accident reports.", sensitive: true, highTrust: true),
        Create(73, PermissionKeys.Fleet.AccidentsDownload, "Fleet", "تنزيل تقارير الحوادث", "Download accident reports", "تنزيل الأدلة وتقارير الحوادث الخاصة.", "Download private accident evidence and reports.", sensitive: true),
        Create(74, PermissionKeys.Fleet.CorrectionsCreate, "Fleet", "إنشاء تصحيح بيانات الأسطول", "Create fleet corrections", "إنشاء تصحيح بيانات الأسطول ضمن النطاق المصرح به.", "Create fleet corrections within the authorized scope.", sensitive: true, highTrust: true),

        Create(75, PermissionKeys.Catalog.CompanyProfileRead, "Catalog", "عرض ملف الشركة", "Read company profile", "عرض بيانات الشركة المالكة وإعداداتها العامة.", "View the owning company profile and general settings."),
        Create(76, PermissionKeys.Catalog.CompanyProfileCreate, "Catalog", "إنشاء ملف الشركة", "Create company profile", "إنشاء ملف الشركة ضمن النطاق المصرح به.", "Create company profile within the authorized scope.", sensitive: true, highTrust: true),
        Create(77, PermissionKeys.Catalog.TagsRead, "Catalog", "عرض الوسوم", "Read tags", "عرض كتالوج الوسوم وروابطه التشغيلية.", "View the tag catalog and operational assignments."),
        Create(78, PermissionKeys.Catalog.TagsCreate, "Catalog", "إنشاء الوسوم", "Create tags", "إنشاء الوسوم ضمن النطاق المصرح به.", "Create tags within the authorized scope."),
        Create(79, PermissionKeys.Documents.CatalogCreate, "Documents", "إنشاء كتالوج الوثائق", "Create document catalog", "إنشاء كتالوج الوثائق ضمن النطاق المصرح به.", "Create document catalog within the authorized scope.", sensitive: true),
        Create(80, PermissionKeys.Operations.PlatformCredentialsRead, "Operations", "عرض سجل بيانات اعتماد المنصات", "Read platform credential history", "عرض بيانات وصفية فقط عن تدوير بيانات اعتماد حسابات المنصات.", "View metadata only for platform-account credential rotations.", clientScope: true, sensitive: true, highTrust: true),
        Create(81, PermissionKeys.Operations.PlatformCredentialsRotate, "Operations", "تدوير بيانات اعتماد المنصات", "Rotate platform credentials", "استبدال بيانات اعتماد حساب منصة مع حفظ سجل مشفر غير قابل للتعديل.", "Replace a platform account credential while preserving encrypted immutable history.", clientScope: true, sensitive: true, highTrust: true),
        Create(82, PermissionKeys.Fleet.RegistrationTransitionsCreate, "Fleet", "إنشاء تحويل تسجيل المركبة", "Create vehicle registration transitions", "إنشاء تحويل تسجيل المركبة ضمن النطاق المصرح به.", "Create vehicle registration transitions within the authorized scope.", sensitive: true, highTrust: true),
        Create(83, PermissionKeys.HrForms.TemplatesRead, "HrForms", "عرض قوالب نماذج الموارد البشرية", "Read HR form templates", "عرض القوالب المنشورة ومسودات تصميم نماذج الموارد البشرية.", "View published HR form templates and design drafts."),
        Create(84, PermissionKeys.HrForms.TemplatesCreate, "HrForms", "إنشاء قوالب نماذج الموارد البشرية", "Create HR form templates", "إنشاء قوالب نماذج الموارد البشرية ضمن النطاق المصرح به.", "Create HR form templates within the authorized scope.", sensitive: true, highTrust: true),
        Create(85, PermissionKeys.Operations.PhoneSimsRead, "Operations", "عرض شرائح الاتصال", "Read phone SIMs", "عرض شرائح الاتصال والمسؤول الحالي وسجل تسليمها للمناديب.", "View phone SIM inventory, current responsible employees, and rider assignment history.", sensitive: true),
        Create(86, PermissionKeys.Operations.PhoneSimsCreate, "Operations", "إنشاء شرائح الاتصال", "Create phone SIMs", "إنشاء شرائح الاتصال ضمن النطاق المصرح به.", "Create phone SIMs within the authorized scope.", sensitive: true),
        Create(87, PermissionKeys.Fleet.DailyDistancesRead, "Fleet", "عرض المسافات اليومية للمركبات", "Read vehicle daily distances", "عرض المسافة اليومية من نظام GPS أو الإدخال اليدوي للمركبات.", "View each vehicle's daily GPS or manually entered distance."),
        Create(88, PermissionKeys.Fleet.DailyDistancesCreate, "Fleet", "إنشاء المسافات اليومية للمركبات", "Create vehicle daily distances", "إنشاء المسافات اليومية للمركبات ضمن النطاق المصرح به.", "Create vehicle daily distances within the authorized scope.", sensitive: true),
        Create(89, PermissionKeys.Fleet.DailyDistancesImport, "Fleet", "استيراد مسافات GPS اليومية", "Import daily GPS distances", "استيراد ملف GPS اليومي وتطبيق المسافات على المركبات المطابقة.", "Import a daily GPS report and apply distances to matching vehicles.", sensitive: true),
        Create(90, PermissionKeys.Fuel.Read, "Fuel", "عرض بطاقات واستهلاك الوقود", "Read fuel cards and usage", "عرض بطاقات الوقود وإسناداتها واستهلاكها الشهري.", "View fuel cards, rider assignments, and monthly usage.", sensitive: true),
        Create(91, PermissionKeys.Fuel.Create, "Fuel", "إنشاء بطاقات الوقود", "Create fuel cards", "إنشاء بطاقات الوقود ضمن النطاق المصرح به.", "Create fuel cards within the authorized scope.", sensitive: true),
        Create(92, PermissionKeys.Fuel.Import, "Fuel", "استيراد تقارير الوقود", "Import fuel reports", "استيراد تقارير بترو أب وسيارة أب وتحديث السجل الشهري للبطاقة.", "Import Petro App and Sayara App reports and update each card's monthly record.", sensitive: true),
        Create(93, PermissionKeys.Maintenance.LocationsRead, "Maintenance", "عرض مواقع الصيانة", "Read maintenance locations", "عرض مستودع جدة وورشة الرياض ونطاقات خدمتهما.", "View maintenance locations and their service scopes."),
        Create(94, PermissionKeys.Maintenance.LocationsCreate, "Maintenance", "إنشاء مواقع الصيانة", "Create maintenance locations", "إنشاء مواقع الصيانة ضمن النطاق المصرح به.", "Create maintenance locations within the authorized scope.", highTrust: true),
        Create(95, PermissionKeys.Maintenance.WorkOrdersRead, "Maintenance", "عرض أوامر الصيانة", "Read maintenance work orders", "عرض أوامر صيانة مركبات الشركة والخارجية.", "View company and external maintenance work orders."),
        Create(96, PermissionKeys.Maintenance.WorkOrdersCreate, "Maintenance", "إنشاء أوامر الصيانة", "Create maintenance work orders", "فتح أوامر الصيانة.", "Create maintenance work orders.", sensitive: true),
        Create(124, PermissionKeys.Maintenance.WorkOrdersUpdate, "Maintenance", "تعديل أوامر الصيانة", "Edit maintenance work orders", "بدء وإكمال وإغلاق أوامر الصيانة وتحديث موادها وتكاليفها.", "Start, complete, close, and update materials and costs of maintenance work orders.", sensitive: true),
        Create(125, PermissionKeys.Maintenance.WorkOrdersDelete, "Maintenance", "إلغاء أوامر الصيانة", "Cancel maintenance work orders", "إلغاء أوامر الصيانة مع حفظ التاريخ.", "Cancel maintenance work orders while retaining history.", sensitive: true),
        Create(97, PermissionKeys.Maintenance.OilRead, "Maintenance", "عرض تغيير الزيت", "Read oil changes", "عرض عمليات وتذكيرات تغيير الزيت.", "View oil-change operations and reminders."),
        Create(98, PermissionKeys.Maintenance.OilComplete, "Maintenance", "تنفيذ تغيير الزيت", "Complete oil changes", "ترحيل الزيت والفلتر وتحديث العداد والتذكير.", "Post oil/filter usage and update odometer reminders.", sensitive: true),
        Create(99, PermissionKeys.Maintenance.ExternalJobsRead, "Maintenance", "عرض صيانة المركبات الخارجية", "Read external maintenance jobs", "عرض المرجع المختصر وأعمال المركبات الخارجية.", "View minimal external-vehicle references and jobs.", sensitive: true),
        Create(100, PermissionKeys.Maintenance.ExternalJobsCreate, "Maintenance", "إنشاء صيانة المركبات الخارجية", "Create external maintenance jobs", "إنشاء صيانة المركبات الخارجية ضمن النطاق المصرح به.", "Create external maintenance jobs within the authorized scope.", sensitive: true),
        Create(101, PermissionKeys.Maintenance.PartSalesCreate, "Maintenance", "إنشاء بيع قطع الغيار", "Create spare-part sales", "إنشاء بيع قطع الغيار ضمن النطاق المصرح به.", "Create spare-part sales within the authorized scope.", sensitive: true),
        Create(102, PermissionKeys.Maintenance.CustomerLaborChargesCreate, "Maintenance", "إنشاء مصنعية العميل", "Create customer labor charges", "إنشاء مصنعية العميل ضمن النطاق المصرح به.", "Create customer labor charges within the authorized scope.", sensitive: true),
        Create(103, PermissionKeys.Maintenance.MechanicLaborPaymentsCreate, "Maintenance", "إنشاء أجرة الميكانيكي", "Create mechanic labor payments", "إنشاء أجرة الميكانيكي ضمن النطاق المصرح به.", "Create mechanic labor payments within the authorized scope.", sensitive: true),
        Create(104, PermissionKeys.Maintenance.ProfitReportsRead, "Maintenance", "عرض تقارير مكسب الورشة", "Read workshop profit reports", "عرض تكلفة FIFO والمصنعية والمكسب الحقيقي.", "View FIFO cost, labor margin, and true workshop profit.", sensitive: true, highTrust: true),
        Create(105, PermissionKeys.Maintenance.ProfitReportsExport, "Maintenance", "تصدير تقارير مكسب الورشة", "Export workshop profit reports", "تصدير تقارير الدخل والمصروف والمكسب.", "Export workshop income, expense, and profit reports.", sensitive: true, highTrust: true),
        Create(106, PermissionKeys.Inventory.ItemsRead, "Inventory", "عرض أصناف المخزون", "Read inventory items", "عرض قطع الغيار والزيوت والإكسسوارات.", "View spare parts, oils, and accessories."),
        Create(107, PermissionKeys.Inventory.ItemsCreate, "Inventory", "إنشاء أصناف المخزون", "Create inventory items", "إنشاء أصناف المخزون ضمن النطاق المصرح به.", "Create inventory items within the authorized scope.", sensitive: true),
        Create(108, PermissionKeys.Inventory.StockRead, "Inventory", "عرض رصيد المخزون", "Read stock balances", "عرض الرصيد في مستودع جدة وورشة الرياض.", "View balances at Jeddah Warehouse and Riyadh Workshop."),
        Create(109, PermissionKeys.Inventory.StockMove, "Inventory", "نقل وصرف المخزون", "Move inventory stock", "ترحيل النقل والصرف وعهد الرايدر بطريقة FIFO.", "Post transfers, usages, and rider issues using FIFO.", sensitive: true),
        Create(110, PermissionKeys.Inventory.StockAdjust, "Inventory", "عكس حركات المخزون", "Adjust inventory stock", "عكس الاستخدامات مع استعادة طبقات التكلفة الأصلية.", "Reverse usage into its original cost layers.", sensitive: true, highTrust: true),
        Create(111, PermissionKeys.Inventory.CostLayersRead, "Inventory", "عرض طبقات تكلفة المخزون", "Read inventory cost layers", "عرض الأسعار والكميات المتبقية لكل دفعة FIFO.", "View FIFO layer prices and remaining quantities.", sensitive: true, highTrust: true),
        Create(112, PermissionKeys.Inventory.ReceiptsCreate, "Inventory", "إنشاء فواتير الشراء", "Create purchase receipts", "إنشاء فواتير الشراء ضمن النطاق المصرح به.", "Create purchase receipts within the authorized scope.", sensitive: true),
        Create(113, PermissionKeys.Inventory.ReturnsCreate, "Inventory", "إنشاء مرتجعات المورد", "Create supplier returns", "إنشاء مرتجعات المورد ضمن النطاق المصرح به.", "Create supplier returns within the authorized scope.", sensitive: true),
        Create(114, PermissionKeys.Inventory.SupplyRequestsSubmit, "Inventory", "إرسال طلبات الصرف", "Submit supply requests", "إرسال طلب موحد لقطع صيانة مركبة أو عهدة رايدر دون خصم المخزون.", "Submit a vehicle-maintenance or rider supply request without deducting stock."),
        Create(115, PermissionKeys.Inventory.SupplyRequestsRead, "Inventory", "عرض طلبات الصرف", "Read supply requests", "عرض طابور طلبات الصرف وحالة الموافقة والمركبة أو الرايدر المرتبط.", "View the supply-request queue, approval state, and related vehicle or rider."),
        Create(116, PermissionKeys.Inventory.SupplyRequestsApprove, "Inventory", "اعتماد وتسليم طلبات الصرف", "Approve and issue supply requests", "اعتماد الطلب وتسليم الأصناف فعليًا وترحيل خصم FIFO في عملية واحدة.", "Approve a request, physically issue its items, and post FIFO stock deduction atomically.", sensitive: true, highTrust: true),
        Create(117, PermissionKeys.Workflows.LegalCasesRead, "Workflows", "عرض القضايا القانونية", "Read legal cases", "عرض قضايا الموارد البشرية والجلسات وسجل التغييرات.", "View HR legal cases, hearings, and immutable change history.", sensitive: true),
        Create(118, PermissionKeys.Workflows.LegalCasesCreate, "Workflows", "إنشاء القضايا القانونية", "Create legal cases", "إنشاء القضايا القانونية ضمن النطاق المصرح به.", "Create legal cases within the authorized scope.", sensitive: true),
        Create(119, PermissionKeys.Workflows.LegalCaseFilesDownload, "Workflows", "تنزيل ملفات القضايا", "Download legal case files", "تنزيل ملفات جلسات القضايا الخاصة.", "Download private legal-case hearing files.", sensitive: true, highTrust: true),
        Create(130, PermissionKeys.Jahez.Read, "Jahez", "عرض جاهز", "Read Jahez", "عرض جاهز ضمن نطاق جاهز.", "Read Jahez within Jahez scope.", clientScope: true, sensitive: true),
        Create(131, PermissionKeys.Jahez.HandoversCreate, "Jahez", "إنشاء تسليم وإغلاق حسابات جاهز", "Create Jahez handovers", "إنشاء تسليم وإغلاق حسابات جاهز ضمن النطاق المصرح به.", "Create Jahez handovers within the authorized scope.", clientScope: true, sensitive: true),
        Create(132, PermissionKeys.Jahez.CollectionsCreate, "Jahez", "إنشاء تحصيل مبالغ جاهز", "Create Collect Jahez payments", "إنشاء تحصيل مبالغ جاهز ضمن النطاق المصرح به.", "Create Collect Jahez payments within the authorized scope.", clientScope: true, sensitive: true),
        Create(133, PermissionKeys.Jahez.RequestsCreate, "Jahez", "إنشاء طلبات جاهز", "Create Jahez requests", "إنشاء طلبات جاهز ضمن نطاق جاهز.", "Create Jahez requests within Jahez scope.", clientScope: true, sensitive: true),
        Create(134, PermissionKeys.Jahez.RequestsApprove, "Jahez", "اعتماد استثناءات جاهز", "Approve Jahez exceptions", "اعتماد استثناءات جاهز ضمن نطاق جاهز.", "Approve Jahez exceptions within Jahez scope.", clientScope: true, sensitive: true, highTrust: true),
        Create(135, PermissionKeys.Jahez.ResetsApprove, "Jahez", "اعتماد تصفير حسابات جاهز", "Approve Jahez resets", "اعتماد تصفير حسابات جاهز ضمن نطاق جاهز.", "Approve Jahez resets within Jahez scope.", clientScope: true, sensitive: true, highTrust: true),
        Create(136, PermissionKeys.Jahez.EarningsCreate, "Jahez", "إنشاء تسجيل أرباح جاهز", "Create Jahez earnings", "إنشاء تسجيل أرباح جاهز ضمن النطاق المصرح به.", "Create Jahez earnings within the authorized scope.", clientScope: true, sensitive: true),
        Create(137, PermissionKeys.Jahez.ImportsCreate, "Jahez", "إنشاء استيراد تقارير جاهز", "Create Import Jahez reports", "إنشاء استيراد تقارير جاهز ضمن النطاق المصرح به.", "Create Import Jahez reports within the authorized scope.", clientScope: true, sensitive: true),
        Create(138, PermissionKeys.Jahez.AdjustmentsCreate, "Jahez", "إنشاء تسويات وأرصدة جاهز", "Create Adjust Jahez balances", "إنشاء تسويات وأرصدة جاهز ضمن النطاق المصرح به.", "Create Adjust Jahez balances within the authorized scope.", clientScope: true, sensitive: true, highTrust: true),
        Create(139, PermissionKeys.Jahez.CashboxRead, "Jahez", "عرض صندوق جاهز", "Read Jahez cashbox", "عرض صندوق جاهز ضمن نطاق جاهز.", "Read Jahez cashbox within Jahez scope.", clientScope: true, sensitive: true),
        Create(140, PermissionKeys.Jahez.CashboxSubmit, "Jahez", "تسليم صندوق جاهز", "Submit Jahez cashbox", "تسليم صندوق جاهز ضمن نطاق جاهز.", "Submit Jahez cashbox within Jahez scope.", clientScope: true, sensitive: true),
        Create(141, PermissionKeys.Jahez.CashboxConfirm, "Jahez", "تأكيد استلام صندوق جاهز", "Confirm Jahez cashbox receipt", "تأكيد استلام صندوق جاهز ضمن نطاق جاهز.", "Confirm Jahez cashbox receipt within Jahez scope.", clientScope: true, sensitive: true),
        Create(142, PermissionKeys.Jahez.CashboxApprove, "Jahez", "اعتماد تسليم صندوق جاهز", "Approve Jahez cashbox handovers", "اعتماد تسليم صندوق جاهز ضمن نطاق جاهز.", "Approve Jahez cashbox handovers within Jahez scope.", clientScope: true, sensitive: true, highTrust: true),
        Create(200, PermissionKeys.Security.RolesUpdate, "Security", "تعديل الأدوار", "Edit roles", "تعديل الأدوار ضمن النطاق المصرح به.", "Update roles within the authorized scope.", highTrust: true),
        Create(201, PermissionKeys.Security.RolesDelete, "Security", "حذف الأدوار", "Delete roles", "حذف الأدوار ضمن النطاق المصرح به.", "Delete roles within the authorized scope.", highTrust: true),
        Create(202, PermissionKeys.Security.PermissionsUpdate, "Security", "تعديل الصلاحيات", "Edit permissions", "تعديل الصلاحيات ضمن النطاق المصرح به.", "Update permissions within the authorized scope.", highTrust: true),
        Create(203, PermissionKeys.Security.PermissionsDelete, "Security", "حذف الصلاحيات", "Delete permissions", "حذف الصلاحيات ضمن النطاق المصرح به.", "Delete permissions within the authorized scope.", highTrust: true),
        Create(204, PermissionKeys.Security.SupportAccessUpdate, "Security", "تعديل وصول الدعم", "Edit support access", "تعديل وصول الدعم ضمن النطاق المصرح به.", "Update support access within the authorized scope.", sensitive: true, highTrust: true),
        Create(205, PermissionKeys.Security.SupportAccessDelete, "Security", "حذف وصول الدعم", "Delete support access", "حذف وصول الدعم ضمن النطاق المصرح به.", "Delete support access within the authorized scope.", sensitive: true, highTrust: true),
        Create(206, PermissionKeys.Security.SupportAccessRead, "Security", "عرض وصول الدعم", "Read support access", "عرض وصول الدعم ضمن النطاق المصرح به.", "Read support access within the authorized scope.", sensitive: true, highTrust: true),
        Create(207, PermissionKeys.Catalog.CompanyProfileUpdate, "Catalog", "تعديل ملف الشركة", "Edit company profile", "تعديل ملف الشركة ضمن النطاق المصرح به.", "Update company profile within the authorized scope.", sensitive: true, highTrust: true),
        Create(208, PermissionKeys.Catalog.CompanyProfileDelete, "Catalog", "حذف ملف الشركة", "Delete company profile", "حذف ملف الشركة ضمن النطاق المصرح به.", "Delete company profile within the authorized scope.", sensitive: true, highTrust: true),
        Create(209, PermissionKeys.Catalog.OperatingCitiesUpdate, "Catalog", "تعديل المدن التشغيلية", "Edit operating cities", "تعديل المدن التشغيلية ضمن النطاق المصرح به.", "Update operating cities within the authorized scope."),
        Create(210, PermissionKeys.Catalog.OperatingCitiesDelete, "Catalog", "حذف المدن التشغيلية", "Delete operating cities", "حذف المدن التشغيلية ضمن النطاق المصرح به.", "Delete operating cities within the authorized scope."),
        Create(211, PermissionKeys.Catalog.TagsUpdate, "Catalog", "تعديل الوسوم", "Edit tags", "تعديل الوسوم ضمن النطاق المصرح به.", "Update tags within the authorized scope."),
        Create(212, PermissionKeys.Catalog.TagsDelete, "Catalog", "حذف الوسوم", "Delete tags", "حذف الوسوم ضمن النطاق المصرح به.", "Delete tags within the authorized scope."),
        Create(213, PermissionKeys.Workforce.RidersUpdate, "Workforce", "تعديل المناديب", "Edit riders", "تعديل المناديب ضمن النطاق المصرح به.", "Update riders within the authorized scope."),
        Create(214, PermissionKeys.Workforce.RidersDelete, "Workforce", "حذف المناديب", "Delete riders", "حذف المناديب ضمن النطاق المصرح به.", "Delete riders within the authorized scope."),
        Create(215, PermissionKeys.Workforce.SponsorsUpdate, "Workforce", "تعديل الكفلاء", "Edit sponsors", "تعديل الكفلاء ضمن النطاق المصرح به.", "Update sponsors within the authorized scope.", sensitive: true),
        Create(216, PermissionKeys.Workforce.SponsorsDelete, "Workforce", "حذف الكفلاء", "Delete sponsors", "حذف الكفلاء ضمن النطاق المصرح به.", "Delete sponsors within the authorized scope.", sensitive: true),
        Create(217, PermissionKeys.Compliance.ResidencyUpdate, "Compliance", "تعديل الإقامات", "Edit residency permits", "تعديل الإقامات ضمن النطاق المصرح به.", "Update residency permits within the authorized scope.", sensitive: true),
        Create(218, PermissionKeys.Compliance.ResidencyDelete, "Compliance", "حذف الإقامات", "Delete residency permits", "حذف الإقامات ضمن النطاق المصرح به.", "Delete residency permits within the authorized scope.", sensitive: true),
        Create(219, PermissionKeys.Compliance.LicensesUpdate, "Compliance", "تعديل الرخص", "Edit driver licenses", "تعديل الرخص ضمن النطاق المصرح به.", "Update driver licenses within the authorized scope.", sensitive: true),
        Create(220, PermissionKeys.Compliance.LicensesDelete, "Compliance", "حذف الرخص", "Delete driver licenses", "حذف الرخص ضمن النطاق المصرح به.", "Delete driver licenses within the authorized scope.", sensitive: true),
        Create(221, PermissionKeys.Compliance.RiderCardsUpdate, "Compliance", "تعديل بطاقات السائق", "Edit rider cards", "تعديل بطاقات السائق ضمن النطاق المصرح به.", "Update rider cards within the authorized scope.", sensitive: true),
        Create(222, PermissionKeys.Compliance.RiderCardsDelete, "Compliance", "حذف بطاقات السائق", "Delete rider cards", "حذف بطاقات السائق ضمن النطاق المصرح به.", "Delete rider cards within the authorized scope.", sensitive: true),
        Create(223, PermissionKeys.Compliance.HealthCardsUpdate, "Compliance", "تعديل البطاقات الصحية", "Edit health cards", "تعديل البطاقات الصحية ضمن النطاق المصرح به.", "Update health cards within the authorized scope.", sensitive: true),
        Create(224, PermissionKeys.Compliance.HealthCardsDelete, "Compliance", "حذف البطاقات الصحية", "Delete health cards", "حذف البطاقات الصحية ضمن النطاق المصرح به.", "Delete health cards within the authorized scope.", sensitive: true),
        Create(225, PermissionKeys.Compliance.InsuranceUpdate, "Compliance", "تعديل التأمين الطبي", "Edit medical insurance", "تعديل التأمين الطبي ضمن النطاق المصرح به.", "Update medical insurance within the authorized scope.", sensitive: true),
        Create(226, PermissionKeys.Compliance.InsuranceDelete, "Compliance", "حذف التأمين الطبي", "Delete medical insurance", "حذف التأمين الطبي ضمن النطاق المصرح به.", "Delete medical insurance within the authorized scope.", sensitive: true),
        Create(227, PermissionKeys.Compliance.PromissoryNotesUpdate, "Compliance", "تعديل سندات الأمر", "Edit promissory notes", "تعديل سندات الأمر ضمن النطاق المصرح به.", "Update promissory notes within the authorized scope.", sensitive: true, highTrust: true),
        Create(228, PermissionKeys.Compliance.PromissoryNotesDelete, "Compliance", "حذف سندات الأمر", "Delete promissory notes", "حذف سندات الأمر ضمن النطاق المصرح به.", "Delete promissory notes within the authorized scope.", sensitive: true, highTrust: true),
        Create(229, PermissionKeys.Documents.CatalogUpdate, "Documents", "تعديل كتالوج الوثائق", "Edit document catalog", "تعديل كتالوج الوثائق ضمن النطاق المصرح به.", "Update document catalog within the authorized scope.", sensitive: true),
        Create(230, PermissionKeys.Documents.CatalogDelete, "Documents", "حذف كتالوج الوثائق", "Delete document catalog", "حذف كتالوج الوثائق ضمن النطاق المصرح به.", "Delete document catalog within the authorized scope.", sensitive: true),
        Create(231, PermissionKeys.Operations.PlatformAccountsUpdate, "Operations", "تعديل حسابات المنصات", "Edit platform accounts", "تعديل حسابات المنصات ضمن النطاق المصرح به.", "Update platform accounts within the authorized scope.", clientScope: true),
        Create(232, PermissionKeys.Operations.PlatformAccountsDelete, "Operations", "حذف حسابات المنصات", "Delete platform accounts", "حذف حسابات المنصات ضمن النطاق المصرح به.", "Delete platform accounts within the authorized scope.", clientScope: true),
        Create(233, PermissionKeys.Operations.PlatformAssignmentsUpdate, "Operations", "تعديل تكليفات المنصات", "Edit platform assignments", "تعديل تكليفات المنصات ضمن النطاق المصرح به.", "Update platform assignments within the authorized scope.", clientScope: true),
        Create(234, PermissionKeys.Operations.PlatformAssignmentsDelete, "Operations", "حذف تكليفات المنصات", "Delete platform assignments", "حذف تكليفات المنصات ضمن النطاق المصرح به.", "Delete platform assignments within the authorized scope.", clientScope: true),
        Create(235, PermissionKeys.Operations.HousingUpdate, "Operations", "تعديل السكن", "Edit housing", "تعديل السكن ضمن النطاق المصرح به.", "Update housing within the authorized scope."),
        Create(236, PermissionKeys.Operations.HousingDelete, "Operations", "حذف السكن", "Delete housing", "حذف السكن ضمن النطاق المصرح به.", "Delete housing within the authorized scope."),
        Create(237, PermissionKeys.Operations.PhoneSimsUpdate, "Operations", "تعديل شرائح الاتصال", "Edit phone SIMs", "تعديل شرائح الاتصال ضمن النطاق المصرح به.", "Update phone SIMs within the authorized scope.", sensitive: true),
        Create(238, PermissionKeys.Operations.PhoneSimsDelete, "Operations", "حذف شرائح الاتصال", "Delete phone SIMs", "حذف شرائح الاتصال ضمن النطاق المصرح به.", "Delete phone SIMs within the authorized scope.", sensitive: true),
        Create(239, PermissionKeys.Reporting.NotificationsUpdate, "Reporting", "تعديل الإشعارات", "Edit notifications", "تعديل الإشعارات ضمن النطاق المصرح به.", "Update notifications within the authorized scope."),
        Create(240, PermissionKeys.Reporting.NotificationsDelete, "Reporting", "حذف الإشعارات", "Delete notifications", "حذف الإشعارات ضمن النطاق المصرح به.", "Delete notifications within the authorized scope."),
        Create(241, PermissionKeys.Fleet.VehiclesUpdate, "Fleet", "تعديل المركبات", "Edit vehicles", "تعديل المركبات ضمن النطاق المصرح به.", "Update vehicles within the authorized scope."),
        Create(242, PermissionKeys.Fleet.VehiclesDelete, "Fleet", "حذف المركبات", "Delete vehicles", "حذف المركبات ضمن النطاق المصرح به.", "Delete vehicles within the authorized scope."),
        Create(243, PermissionKeys.Fleet.AssignmentsUpdate, "Fleet", "تعديل عهد المركبات", "Edit vehicle assignments", "تعديل عهد المركبات ضمن النطاق المصرح به.", "Update vehicle assignments within the authorized scope."),
        Create(244, PermissionKeys.Fleet.AssignmentsDelete, "Fleet", "حذف عهد المركبات", "Delete vehicle assignments", "حذف عهد المركبات ضمن النطاق المصرح به.", "Delete vehicle assignments within the authorized scope."),
        Create(245, PermissionKeys.Fleet.IssuesUpdate, "Fleet", "تعديل بلاغات المركبات", "Edit vehicle issues", "تعديل بلاغات المركبات ضمن النطاق المصرح به.", "Update vehicle issues within the authorized scope."),
        Create(246, PermissionKeys.Fleet.IssuesDelete, "Fleet", "حذف بلاغات المركبات", "Delete vehicle issues", "حذف بلاغات المركبات ضمن النطاق المصرح به.", "Delete vehicle issues within the authorized scope."),
        Create(247, PermissionKeys.Fleet.ComplianceUpdate, "Fleet", "تعديل التزام المركبات", "Edit vehicle compliance", "تعديل التزام المركبات ضمن النطاق المصرح به.", "Update vehicle compliance within the authorized scope."),
        Create(248, PermissionKeys.Fleet.ComplianceDelete, "Fleet", "حذف التزام المركبات", "Delete vehicle compliance", "حذف التزام المركبات ضمن النطاق المصرح به.", "Delete vehicle compliance within the authorized scope."),
        Create(249, PermissionKeys.Fleet.CorrectionsUpdate, "Fleet", "تعديل تصحيح بيانات الأسطول", "Edit fleet corrections", "تعديل تصحيح بيانات الأسطول ضمن النطاق المصرح به.", "Update fleet corrections within the authorized scope.", sensitive: true, highTrust: true),
        Create(250, PermissionKeys.Fleet.CorrectionsDelete, "Fleet", "حذف تصحيح بيانات الأسطول", "Delete fleet corrections", "حذف تصحيح بيانات الأسطول ضمن النطاق المصرح به.", "Delete fleet corrections within the authorized scope.", sensitive: true, highTrust: true),
        Create(251, PermissionKeys.Fleet.RegistrationTransitionsUpdate, "Fleet", "تعديل تحويل تسجيل المركبة", "Edit vehicle registration transitions", "تعديل تحويل تسجيل المركبة ضمن النطاق المصرح به.", "Update vehicle registration transitions within the authorized scope.", sensitive: true, highTrust: true),
        Create(252, PermissionKeys.Fleet.RegistrationTransitionsDelete, "Fleet", "حذف تحويل تسجيل المركبة", "Delete vehicle registration transitions", "حذف تحويل تسجيل المركبة ضمن النطاق المصرح به.", "Delete vehicle registration transitions within the authorized scope.", sensitive: true, highTrust: true),
        Create(253, PermissionKeys.Fleet.DailyDistancesUpdate, "Fleet", "تعديل المسافات اليومية للمركبات", "Edit vehicle daily distances", "تعديل المسافات اليومية للمركبات ضمن النطاق المصرح به.", "Update vehicle daily distances within the authorized scope.", sensitive: true),
        Create(254, PermissionKeys.Fleet.DailyDistancesDelete, "Fleet", "حذف المسافات اليومية للمركبات", "Delete vehicle daily distances", "حذف المسافات اليومية للمركبات ضمن النطاق المصرح به.", "Delete vehicle daily distances within the authorized scope.", sensitive: true),
        Create(255, PermissionKeys.Jahez.HandoversUpdate, "Jahez", "تعديل تسليم وإغلاق حسابات جاهز", "Edit Jahez handovers", "تعديل تسليم وإغلاق حسابات جاهز ضمن النطاق المصرح به.", "Update Jahez handovers within the authorized scope.", clientScope: true, sensitive: true),
        Create(256, PermissionKeys.Jahez.HandoversDelete, "Jahez", "حذف تسليم وإغلاق حسابات جاهز", "Delete Jahez handovers", "حذف تسليم وإغلاق حسابات جاهز ضمن النطاق المصرح به.", "Delete Jahez handovers within the authorized scope.", clientScope: true, sensitive: true),
        Create(257, PermissionKeys.Jahez.CollectionsUpdate, "Jahez", "تعديل تحصيل مبالغ جاهز", "Edit Collect Jahez payments", "تعديل تحصيل مبالغ جاهز ضمن النطاق المصرح به.", "Update Collect Jahez payments within the authorized scope.", clientScope: true, sensitive: true),
        Create(258, PermissionKeys.Jahez.CollectionsDelete, "Jahez", "حذف تحصيل مبالغ جاهز", "Delete Collect Jahez payments", "حذف تحصيل مبالغ جاهز ضمن النطاق المصرح به.", "Delete Collect Jahez payments within the authorized scope.", clientScope: true, sensitive: true),
        Create(259, PermissionKeys.Jahez.EarningsUpdate, "Jahez", "تعديل تسجيل أرباح جاهز", "Edit Jahez earnings", "تعديل تسجيل أرباح جاهز ضمن النطاق المصرح به.", "Update Jahez earnings within the authorized scope.", clientScope: true, sensitive: true),
        Create(260, PermissionKeys.Jahez.EarningsDelete, "Jahez", "حذف تسجيل أرباح جاهز", "Delete Jahez earnings", "حذف تسجيل أرباح جاهز ضمن النطاق المصرح به.", "Delete Jahez earnings within the authorized scope.", clientScope: true, sensitive: true),
        Create(261, PermissionKeys.Jahez.ImportsUpdate, "Jahez", "تعديل استيراد تقارير جاهز", "Edit Import Jahez reports", "تعديل استيراد تقارير جاهز ضمن النطاق المصرح به.", "Update Import Jahez reports within the authorized scope.", clientScope: true, sensitive: true),
        Create(262, PermissionKeys.Jahez.ImportsDelete, "Jahez", "حذف استيراد تقارير جاهز", "Delete Import Jahez reports", "حذف استيراد تقارير جاهز ضمن النطاق المصرح به.", "Delete Import Jahez reports within the authorized scope.", clientScope: true, sensitive: true),
        Create(263, PermissionKeys.Jahez.ImportsRead, "Jahez", "عرض استيراد تقارير جاهز", "Read Import Jahez reports", "عرض استيراد تقارير جاهز ضمن النطاق المصرح به.", "Read Import Jahez reports within the authorized scope.", clientScope: true, sensitive: true),
        Create(264, PermissionKeys.Jahez.AdjustmentsUpdate, "Jahez", "تعديل تسويات وأرصدة جاهز", "Edit Adjust Jahez balances", "تعديل تسويات وأرصدة جاهز ضمن النطاق المصرح به.", "Update Adjust Jahez balances within the authorized scope.", clientScope: true, sensitive: true, highTrust: true),
        Create(265, PermissionKeys.Jahez.AdjustmentsDelete, "Jahez", "حذف تسويات وأرصدة جاهز", "Delete Adjust Jahez balances", "حذف تسويات وأرصدة جاهز ضمن النطاق المصرح به.", "Delete Adjust Jahez balances within the authorized scope.", clientScope: true, sensitive: true, highTrust: true),
        Create(266, PermissionKeys.Fuel.Update, "Fuel", "تعديل بطاقات الوقود", "Edit fuel cards", "تعديل بطاقات الوقود ضمن النطاق المصرح به.", "Update fuel cards within the authorized scope.", sensitive: true),
        Create(267, PermissionKeys.Fuel.Delete, "Fuel", "حذف بطاقات الوقود", "Delete fuel cards", "حذف بطاقات الوقود ضمن النطاق المصرح به.", "Delete fuel cards within the authorized scope.", sensitive: true),
        Create(268, PermissionKeys.Maintenance.LocationsUpdate, "Maintenance", "تعديل مواقع الصيانة", "Edit maintenance locations", "تعديل مواقع الصيانة ضمن النطاق المصرح به.", "Update maintenance locations within the authorized scope.", highTrust: true),
        Create(269, PermissionKeys.Maintenance.LocationsDelete, "Maintenance", "حذف مواقع الصيانة", "Delete maintenance locations", "حذف مواقع الصيانة ضمن النطاق المصرح به.", "Delete maintenance locations within the authorized scope.", highTrust: true),
        Create(270, PermissionKeys.Maintenance.ExternalJobsUpdate, "Maintenance", "تعديل صيانة المركبات الخارجية", "Edit external maintenance jobs", "تعديل صيانة المركبات الخارجية ضمن النطاق المصرح به.", "Update external maintenance jobs within the authorized scope.", sensitive: true),
        Create(271, PermissionKeys.Maintenance.ExternalJobsDelete, "Maintenance", "حذف صيانة المركبات الخارجية", "Delete external maintenance jobs", "حذف صيانة المركبات الخارجية ضمن النطاق المصرح به.", "Delete external maintenance jobs within the authorized scope.", sensitive: true),
        Create(272, PermissionKeys.Maintenance.PartSalesUpdate, "Maintenance", "تعديل بيع قطع الغيار", "Edit spare-part sales", "تعديل بيع قطع الغيار ضمن النطاق المصرح به.", "Update spare-part sales within the authorized scope.", sensitive: true),
        Create(273, PermissionKeys.Maintenance.PartSalesDelete, "Maintenance", "حذف بيع قطع الغيار", "Delete spare-part sales", "حذف بيع قطع الغيار ضمن النطاق المصرح به.", "Delete spare-part sales within the authorized scope.", sensitive: true),
        Create(274, PermissionKeys.Maintenance.CustomerLaborChargesUpdate, "Maintenance", "تعديل مصنعية العميل", "Edit customer labor charges", "تعديل مصنعية العميل ضمن النطاق المصرح به.", "Update customer labor charges within the authorized scope.", sensitive: true),
        Create(275, PermissionKeys.Maintenance.CustomerLaborChargesDelete, "Maintenance", "حذف مصنعية العميل", "Delete customer labor charges", "حذف مصنعية العميل ضمن النطاق المصرح به.", "Delete customer labor charges within the authorized scope.", sensitive: true),
        Create(276, PermissionKeys.Maintenance.MechanicLaborPaymentsUpdate, "Maintenance", "تعديل أجرة الميكانيكي", "Edit mechanic labor payments", "تعديل أجرة الميكانيكي ضمن النطاق المصرح به.", "Update mechanic labor payments within the authorized scope.", sensitive: true),
        Create(277, PermissionKeys.Maintenance.MechanicLaborPaymentsDelete, "Maintenance", "حذف أجرة الميكانيكي", "Delete mechanic labor payments", "حذف أجرة الميكانيكي ضمن النطاق المصرح به.", "Delete mechanic labor payments within the authorized scope.", sensitive: true),
        Create(278, PermissionKeys.Inventory.ItemsUpdate, "Inventory", "تعديل أصناف المخزون", "Edit inventory items", "تعديل أصناف المخزون ضمن النطاق المصرح به.", "Update inventory items within the authorized scope.", sensitive: true),
        Create(279, PermissionKeys.Inventory.ItemsDelete, "Inventory", "حذف أصناف المخزون", "Delete inventory items", "حذف أصناف المخزون ضمن النطاق المصرح به.", "Delete inventory items within the authorized scope.", sensitive: true),
        Create(280, PermissionKeys.Inventory.ReceiptsUpdate, "Inventory", "تعديل فواتير الشراء", "Edit purchase receipts", "تعديل فواتير الشراء ضمن النطاق المصرح به.", "Update purchase receipts within the authorized scope.", sensitive: true),
        Create(281, PermissionKeys.Inventory.ReceiptsDelete, "Inventory", "حذف فواتير الشراء", "Delete purchase receipts", "حذف فواتير الشراء ضمن النطاق المصرح به.", "Delete purchase receipts within the authorized scope.", sensitive: true),
        Create(282, PermissionKeys.Inventory.ReceiptsRead, "Inventory", "عرض فواتير الشراء", "Read purchase receipts", "عرض فواتير الشراء ضمن النطاق المصرح به.", "Read purchase receipts within the authorized scope.", sensitive: true),
        Create(283, PermissionKeys.Inventory.ReturnsUpdate, "Inventory", "تعديل مرتجعات المورد", "Edit supplier returns", "تعديل مرتجعات المورد ضمن النطاق المصرح به.", "Update supplier returns within the authorized scope.", sensitive: true),
        Create(284, PermissionKeys.Inventory.ReturnsDelete, "Inventory", "حذف مرتجعات المورد", "Delete supplier returns", "حذف مرتجعات المورد ضمن النطاق المصرح به.", "Delete supplier returns within the authorized scope.", sensitive: true),
        Create(285, PermissionKeys.Workflows.LeaveRequestsUpdate, "Workflows", "تعديل طلبات الإجازة", "Edit leave requests", "تعديل طلبات الإجازة ضمن النطاق المصرح به.", "Update leave requests within the authorized scope.", sensitive: true),
        Create(286, PermissionKeys.Workflows.LeaveRequestsDelete, "Workflows", "حذف طلبات الإجازة", "Delete leave requests", "حذف طلبات الإجازة ضمن النطاق المصرح به.", "Delete leave requests within the authorized scope.", sensitive: true),
        Create(287, PermissionKeys.Workflows.AbsenceCasesUpdate, "Workflows", "تعديل حالات الغياب", "Edit absence cases", "تعديل حالات الغياب ضمن النطاق المصرح به.", "Update absence cases within the authorized scope.", sensitive: true),
        Create(288, PermissionKeys.Workflows.AbsenceCasesDelete, "Workflows", "حذف حالات الغياب", "Delete absence cases", "حذف حالات الغياب ضمن النطاق المصرح به.", "Delete absence cases within the authorized scope.", sensitive: true),
        Create(289, PermissionKeys.Workflows.EmployeeStatusChangesUpdate, "Workflows", "تعديل طلبات تغيير الحالة", "Edit employee status changes", "تعديل طلبات تغيير الحالة ضمن النطاق المصرح به.", "Update employee status changes within the authorized scope.", sensitive: true),
        Create(290, PermissionKeys.Workflows.EmployeeStatusChangesDelete, "Workflows", "حذف طلبات تغيير الحالة", "Delete employee status changes", "حذف طلبات تغيير الحالة ضمن النطاق المصرح به.", "Delete employee status changes within the authorized scope.", sensitive: true),
        Create(291, PermissionKeys.Workflows.LegalCasesUpdate, "Workflows", "تعديل القضايا القانونية", "Edit legal cases", "تعديل القضايا القانونية ضمن النطاق المصرح به.", "Update legal cases within the authorized scope.", sensitive: true),
        Create(292, PermissionKeys.Workflows.LegalCasesDelete, "Workflows", "حذف القضايا القانونية", "Delete legal cases", "حذف القضايا القانونية ضمن النطاق المصرح به.", "Delete legal cases within the authorized scope.", sensitive: true),
        Create(293, PermissionKeys.HrForms.TemplatesUpdate, "HrForms", "تعديل قوالب نماذج الموارد البشرية", "Edit HR form templates", "تعديل قوالب نماذج الموارد البشرية ضمن النطاق المصرح به.", "Update HR form templates within the authorized scope.", sensitive: true, highTrust: true),
        Create(294, PermissionKeys.HrForms.TemplatesDelete, "HrForms", "حذف قوالب نماذج الموارد البشرية", "Delete HR form templates", "حذف قوالب نماذج الموارد البشرية ضمن النطاق المصرح به.", "Delete HR form templates within the authorized scope.", sensitive: true, highTrust: true),
        Create(295, PermissionKeys.Documents.CatalogRead, "Documents", "عرض كتالوج الوثائق", "Read document catalog", "عرض كتالوج الوثائق ضمن النطاق المصرح به.", "Read document catalog within the authorized scope.", sensitive: true),
        Create(296, PermissionKeys.Fleet.CorrectionsRead, "Fleet", "عرض تصحيح بيانات الأسطول", "Read fleet corrections", "عرض تصحيح بيانات الأسطول ضمن النطاق المصرح به.", "Read fleet corrections within the authorized scope.", sensitive: true, highTrust: true),
        Create(297, PermissionKeys.Fleet.RegistrationTransitionsRead, "Fleet", "عرض تحويل تسجيل المركبة", "Read vehicle registration transitions", "عرض تحويل تسجيل المركبة ضمن النطاق المصرح به.", "Read vehicle registration transitions within the authorized scope.", sensitive: true, highTrust: true),
        Create(298, PermissionKeys.Jahez.HandoversRead, "Jahez", "عرض تسليم وإغلاق حسابات جاهز", "Read Jahez handovers", "عرض تسليم وإغلاق حسابات جاهز ضمن النطاق المصرح به.", "Read Jahez handovers within the authorized scope.", clientScope: true, sensitive: true),
        Create(299, PermissionKeys.Jahez.CollectionsRead, "Jahez", "عرض تحصيل مبالغ جاهز", "Read Collect Jahez payments", "عرض تحصيل مبالغ جاهز ضمن النطاق المصرح به.", "Read Collect Jahez payments within the authorized scope.", clientScope: true, sensitive: true),
        Create(300, PermissionKeys.Jahez.EarningsRead, "Jahez", "عرض تسجيل أرباح جاهز", "Read Jahez earnings", "عرض تسجيل أرباح جاهز ضمن النطاق المصرح به.", "Read Jahez earnings within the authorized scope.", clientScope: true, sensitive: true),
        Create(301, PermissionKeys.Jahez.AdjustmentsRead, "Jahez", "عرض تسويات وأرصدة جاهز", "Read Adjust Jahez balances", "عرض تسويات وأرصدة جاهز ضمن النطاق المصرح به.", "Read Adjust Jahez balances within the authorized scope.", clientScope: true, sensitive: true, highTrust: true),
        Create(302, PermissionKeys.Maintenance.PartSalesRead, "Maintenance", "عرض بيع قطع الغيار", "Read spare-part sales", "عرض بيع قطع الغيار ضمن النطاق المصرح به.", "Read spare-part sales within the authorized scope.", sensitive: true),
        Create(303, PermissionKeys.Maintenance.CustomerLaborChargesRead, "Maintenance", "عرض مصنعية العميل", "Read customer labor charges", "عرض مصنعية العميل ضمن النطاق المصرح به.", "Read customer labor charges within the authorized scope.", sensitive: true),
        Create(304, PermissionKeys.Maintenance.MechanicLaborPaymentsRead, "Maintenance", "عرض أجرة الميكانيكي", "Read mechanic labor payments", "عرض أجرة الميكانيكي ضمن النطاق المصرح به.", "Read mechanic labor payments within the authorized scope.", sensitive: true),
        Create(305, PermissionKeys.Inventory.ReturnsRead, "Inventory", "عرض مرتجعات المورد", "Read supplier returns", "عرض مرتجعات المورد ضمن النطاق المصرح به.", "Read supplier returns within the authorized scope.", sensitive: true),
    ];

    private static PermissionSeed Create(
        int displayOrder,
        string key,
        string category,
        string nameAr,
        string nameEn,
        string descriptionAr,
        string descriptionEn,
        bool housingScope = false,
        bool clientScope = false,
        bool sensitive = false,
        bool highTrust = false) => new(
            CreateId(displayOrder),
            key,
            category,
            nameAr,
            nameEn,
            descriptionAr,
            descriptionEn,
            housingScope,
            clientScope,
            sensitive,
            highTrust,
            highTrust ? "HIGH_TRUST_ONLY" : sensitive ? "SENSITIVE_DATA" : null,
            displayOrder);

    private static Guid CreateId(int displayOrder) =>
        Guid.Parse($"019c18d5-62e1-7000-a000-{displayOrder:D12}");
}
