<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <RootNamespace>LogisticsERP.Worker</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\LogisticsERP.Application\LogisticsERP.Application.csproj" />
    <ProjectReference Include="..\LogisticsERP.Infrastructure\LogisticsERP.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>
</Project>
