export type ApiMethod = "GET" | "POST" | "PUT" | "PATCH";
export type LocalizedLabel = { ar: string; en: string };

export type ControllerEndpoint = {
  id: string;
  method: ApiMethod;
  path: string;
  permission?: string;
  label: LocalizedLabel;
  /** File requests use multipart/form-data. Every other command accepts a JSON body. */
  content?: "file" | "download";
};

export type ControllerArea = {
  id: string;
  label: LocalizedLabel;
  endpoints: ControllerEndpoint[];
};

const label = (ar: string, en: string): LocalizedLabel => ({ ar, en });
const endpoint = (id: string, method: ApiMethod, path: string, permission: string | undefined, ar: string, en: string, content?: ControllerEndpoint["content"]): ControllerEndpoint => ({ id, method, path, permission, label: label(ar, en), content });
const get = (id: string, path: string, permission: string | undefined, ar: string, en: string, content?: ControllerEndpoint["content"]) => endpoint(id, "GET", path, permission, ar, en, content);
const post = (id: string, path: string, permission: string | undefined, ar: string, en: string, content?: ControllerEndpoint["content"]) => endpoint(id, "POST", path, permission, ar, en, content);
const put = (id: string, path: string, permission: string | undefined, ar: string, en: string) => endpoint(id, "PUT", path, permission, ar, en);
const patch = (id: string, path: string, permission: string | undefined, ar: string, en: string) => endpoint(id, "PATCH", path, permission, ar, en);

/**
 * The manager API catalogue mirrors the current ASP.NET controllers exactly.
 * Dynamic route segments are deliberately kept visible so a user must select a
 * concrete record before a detail or mutation endpoint can be executed.
 */
export const controllerAreas: ControllerArea[] = [
  { id: "auth", label: label("المصادقة", "Auth"), endpoints: [
    post("login", "/api/auth/login", undefined, "تسجيل الدخول", "Sign in"), post("refresh", "/api/auth/refresh", undefined, "تحديث الجلسة", "Refresh session"), post("logout", "/api/auth/logout", undefined, "تسجيل الخروج", "Sign out"), post("logout-all", "/api/auth/logout-all", undefined, "تسجيل الخروج من كل الأجهزة", "Sign out everywhere"), post("change-password", "/api/auth/change-password", undefined, "تغيير كلمة المرور", "Change password"), get("sessions", "/api/auth/sessions", undefined, "الجلسات النشطة", "Active sessions"), post("revoke-session", "/api/auth/sessions/{sessionId}/revoke", undefined, "إلغاء جلسة", "Revoke session"),
  ] },
  { id: "employees", label: label("الموظفون", "Employees"), endpoints: [
    get("employees", "/api/employees", "employees.read", "كل الموظفين", "All employees"), get("employee", "/api/employees/{employeeId}", "employees.read", "تفاصيل موظف", "Employee details"), post("create-employee", "/api/employees", "employees.create", "إضافة موظف", "Create employee"), put("update-employee", "/api/employees/{employeeId}", "employees.update", "تعديل موظف", "Update employee"), post("employee-status", "/api/employees/{employeeId}/status-transitions", "employees.update", "تغيير حالة الموظف", "Change employee status"), post("employee-relationship", "/api/employees/{employeeId}/relationship-transitions", "employees.update", "تغيير علاقة الموظف", "Change employee relationship"), put("sponsored-details", "/api/employees/{employeeId}/sponsored-details", "employees.update", "بيانات الموظف المكفول", "Update sponsored details"), put("outside-rider-details", "/api/employees/{employeeId}/outside-rider-details", "riders.manage", "بيانات المندوب الخارجي", "Update outside-rider details"), post("operational-assignment", "/api/employees/{employeeId}/operational-assignments", "employees.update", "إسناد عمل تشغيلي", "Assign operational work"), get("employee-sponsorships", "/api/employees/{employeeId}/sponsorships", "sponsors.read", "سجل الكفالات", "Sponsorship history"), post("change-sponsorship", "/api/employees/{employeeId}/sponsorships", "sponsors.manage", "تغيير الكفالة", "Change sponsorship"), patch("archive-employee", "/api/employees/{employeeId}/archive", "employees.archive", "أرشفة موظف", "Archive employee"),
  ] },
  { id: "employee-documents", label: label("وثائق الموظفين", "Employee documents"), endpoints: [
    get("employee-documents", "/api/employees/{employeeId}/documents", "documents.read", "وثائق موظف", "Employee documents"), post("upload-employee-document", "/api/employees/{employeeId}/documents", "documents.upload", "رفع وثيقة موظف", "Upload employee document", "file"), post("upload-document-version", "/api/employees/{employeeId}/documents/{documentId}/versions", "documents.upload", "رفع إصدار وثيقة", "Upload document version", "file"), put("document-metadata", "/api/employees/{employeeId}/documents/{documentId}", "documents.upload", "تعديل بيانات الوثيقة", "Update document metadata"), get("document-versions", "/api/employees/{employeeId}/documents/{documentId}/versions", "documents.read", "إصدارات الوثيقة", "Document versions"), get("download-document", "/api/employees/{employeeId}/documents/{documentId}/download", "documents.download_sensitive", "تنزيل وثيقة", "Download document", "download"), patch("archive-document", "/api/employees/{employeeId}/documents/{documentId}/archive", "documents.upload", "أرشفة وثيقة", "Archive document"),
  ] },
  { id: "riders", label: label("المندوبون", "Riders"), endpoints: [
    get("riders", "/api/riders", "riders.read", "كل المندوبين", "All riders"), get("outside-riders", "/api/riders/outside", "riders.read", "المندوبون الخارجيون", "Outside riders"), post("create-rider", "/api/riders/employee/{employeeId}", "riders.manage", "إضافة ملف مندوب", "Create rider profile"), put("update-rider", "/api/riders/{riderProfileId}", "riders.manage", "تعديل ملف مندوب", "Update rider profile"),
  ] },
  { id: "rider-cards", label: label("بطاقات المندوب", "Rider cards"), endpoints: [
    get("rider-cards", "/api/riders/{riderProfileId}/cards", "rider_cards.read", "بطاقات المندوب", "Rider cards"), post("create-rider-card", "/api/riders/{riderProfileId}/cards", "rider_cards.manage", "إضافة بطاقة مندوب", "Create rider card"), put("update-rider-card", "/api/riders/{riderProfileId}/cards/{id}", "rider_cards.manage", "تعديل بطاقة مندوب", "Update rider card"), get("health-cards", "/api/riders/{riderProfileId}/health-cards", "health_cards.read", "البطاقات الصحية", "Health cards"), post("create-health-card", "/api/riders/{riderProfileId}/health-cards", "health_cards.manage", "إضافة بطاقة صحية", "Create health card"), put("update-health-card", "/api/riders/{riderProfileId}/health-cards/{id}", "health_cards.manage", "تعديل بطاقة صحية", "Update health card"), patch("archive-rider-card", "/api/riders/{riderProfileId}/cards/{id}/archive", "rider_cards.manage", "أرشفة بطاقة مندوب", "Archive rider card"), patch("archive-health-card", "/api/riders/{riderProfileId}/health-cards/{id}/archive", "health_cards.manage", "أرشفة بطاقة صحية", "Archive health card"),
  ] },
  { id: "rider-documents", label: label("وثائق المندوب", "Rider documents"), endpoints: [
    post("rider-residency-document", "/api/riders/{riderProfileId}/documents/residency-permit", "documents.upload", "رفع وثيقة إقامة", "Upload residency document", "file"), post("rider-license-document", "/api/riders/{riderProfileId}/documents/driver-license", "documents.upload", "رفع وثيقة رخصة", "Upload license document", "file"), post("rider-card-document", "/api/riders/{riderProfileId}/documents/rider-card", "documents.upload", "رفع وثيقة بطاقة", "Upload rider-card document", "file"), post("health-card-document", "/api/riders/{riderProfileId}/documents/health-card", "documents.upload", "رفع وثيقة صحية", "Upload health-card document", "file"), post("promissory-document", "/api/riders/{riderProfileId}/documents/promissory-note", "documents.upload", "رفع وثيقة تعهد", "Upload promissory-note document", "file"), post("insurance-document", "/api/riders/{riderProfileId}/documents/medical-insurance", "documents.upload", "رفع وثيقة تأمين", "Upload medical-insurance document", "file"),
  ] },
  { id: "housing", label: label("السكن", "Housing"), endpoints: [
    get("housing", "/api/housing", "housing.read", "كل وحدات السكن", "All housing"), get("housing-detail", "/api/housing/{id}", "housing.read", "تفاصيل السكن", "Housing details"), post("create-housing", "/api/housing", "housing.manage", "إضافة سكن", "Create housing"), put("update-housing", "/api/housing/{id}", "housing.manage", "تعديل السكن", "Update housing"), patch("archive-housing", "/api/housing/{id}/archive", "housing.manage", "أرشفة السكن", "Archive housing"), get("housing-residents", "/api/housing/{id}/residents", "housing.read", "سكان السكن", "Housing residents"), post("assign-resident", "/api/housing/{id}/residents", "housing.manage", "تسكين موظف", "Assign resident"), post("close-residence", "/api/housing/residence-periods/{periodId}/close", "housing.manage", "إنهاء فترة سكن", "Close residence period"), get("housing-supervisors", "/api/housing/{id}/supervisors", "housing.read", "مشرفو السكن", "Housing supervisors"), post("assign-supervisor", "/api/housing/{id}/supervisors", "housing.manage", "تعيين مشرف", "Assign supervisor"), post("close-supervisor", "/api/housing/supervisor-periods/{periodId}/close", "housing.manage", "إنهاء فترة إشراف", "Close supervisor period"),
  ] },
  { id: "sponsors", label: label("الكفلاء", "Sponsors"), endpoints: [
    get("sponsors", "/api/sponsors", "sponsors.read", "كل الكفلاء", "All sponsors"), get("sponsor", "/api/sponsors/{id}", "sponsors.read", "تفاصيل كفيل", "Sponsor details"), post("create-sponsor", "/api/sponsors", "sponsors.manage", "إضافة كفيل", "Create sponsor"), put("update-sponsor", "/api/sponsors/{id}", "sponsors.manage", "تعديل كفيل", "Update sponsor"), patch("archive-sponsor", "/api/sponsors/{id}/archive", "sponsors.manage", "أرشفة كفيل", "Archive sponsor"),
  ] },
  { id: "hr-catalogs", label: label("كتالوجات الموارد البشرية", "HR catalogs"), endpoints: [
    get("job-titles", "/api/hr-catalogs/job-titles", "employees.read", "المسميات الوظيفية", "Job titles"), post("create-job-title", "/api/hr-catalogs/job-titles", "employees.update", "إضافة مسمى وظيفي", "Create job title"), put("update-job-title", "/api/hr-catalogs/job-titles/{id}", "employees.update", "تعديل مسمى وظيفي", "Update job title"), put("set-job-work-types", "/api/hr-catalogs/job-titles/{id}/operational-work-types", "employees.update", "تحديد أنواع العمل", "Set operational work types"), get("residency-professions", "/api/hr-catalogs/residency-professions", "residency.read", "مهن الإقامة", "Residency professions"), post("create-residency-profession", "/api/hr-catalogs/residency-professions", "residency.manage", "إضافة مهنة إقامة", "Create residency profession"), put("update-residency-profession", "/api/hr-catalogs/residency-professions/{id}", "residency.manage", "تعديل مهنة إقامة", "Update residency profession"), get("operational-work-types", "/api/hr-catalogs/operational-work-types", "employees.read", "أنواع العمل التشغيلي", "Operational work types"), get("license-categories", "/api/hr-catalogs/driver-license-categories", "licenses.read", "فئات رخص القيادة", "Driver license categories"), get("document-types", "/api/hr-catalogs/document-types", "documents.read", "أنواع الوثائق", "Document types"), get("operating-cities", "/api/hr-catalogs/operating-cities", "operating_cities.read", "مدن التشغيل", "Operating cities"),
  ] },
  { id: "workflows", label: label("مسارات الموارد البشرية", "HR workflows"), endpoints: [
    get("leave-types", "/api/hr-workflows/leave-types", "leave_requests.read", "أنواع الإجازات", "Leave types"), post("create-leave-type", "/api/hr-workflows/leave-types", "leave_requests.manage", "إضافة نوع إجازة", "Create leave type"), put("update-leave-type", "/api/hr-workflows/leave-types/{id}", "leave_requests.manage", "تعديل نوع إجازة", "Update leave type"), get("leave-workflows", "/api/hr-workflows/leave-approval-workflows", "leave_requests.read", "مسارات اعتماد الإجازة", "Leave approval workflows"), post("create-leave-workflow", "/api/hr-workflows/leave-approval-workflows", "leave_requests.manage", "إضافة مسار إجازة", "Create leave workflow"), put("update-leave-workflow", "/api/hr-workflows/leave-approval-workflows/{id}", "leave_requests.manage", "تعديل مسار إجازة", "Update leave workflow"), get("leave-requests", "/api/hr-workflows/leave-requests", "leave_requests.read", "طلبات الإجازة", "Leave requests"), post("create-leave-request", "/api/hr-workflows/leave-requests", "leave_requests.manage", "إضافة طلب إجازة", "Create leave request"), put("update-leave-request", "/api/hr-workflows/leave-requests/{id}", "leave_requests.manage", "تعديل طلب إجازة", "Update leave request"), post("transition-leave", "/api/hr-workflows/leave-requests/{id}/transitions", "leave_requests.manage", "تغيير حالة الإجازة", "Transition leave request"), post("decide-leave", "/api/hr-workflows/leave-requests/{id}/approval-decisions", "leave_requests.approve", "قرار اعتماد الإجازة", "Decide leave request"), get("absence-cases", "/api/hr-workflows/absence-cases", "absence_cases.read", "حالات الغياب", "Absence cases"), post("create-absence", "/api/hr-workflows/absence-cases", "absence_cases.manage", "إضافة حالة غياب", "Create absence case"), put("update-absence", "/api/hr-workflows/absence-cases/{id}", "absence_cases.manage", "تعديل حالة غياب", "Update absence case"), post("transition-absence", "/api/hr-workflows/absence-cases/{id}/transitions", "absence_cases.manage", "تغيير حالة غياب", "Transition absence case"), get("status-changes", "/api/hr-workflows/employee-status-change-requests", "employee_status_changes.read", "طلبات تغيير حالة الموظف", "Employee status change requests"), post("create-status-change", "/api/hr-workflows/employee-status-change-requests", "employee_status_changes.manage", "إضافة طلب تغيير حالة", "Create status change request"), post("resolve-status-change", "/api/hr-workflows/employee-status-change-requests/{id}/resolve", "employee_status_changes.approve", "حل طلب تغيير الحالة", "Resolve status change"),
  ] },
  { id: "import", label: label("الاستيراد", "Import"), endpoints: [
    post("validate-import", "/api/import/employees-riders/validate", undefined, "التحقق من ملف الاستيراد", "Validate import workbook", "file"), post("commit-import", "/api/import/employees-riders", undefined, "تنفيذ الاستيراد", "Commit import workbook", "file"),
  ] },
  { id: "insurance", label: label("التأمين", "Insurance"), endpoints: [
    get("insurance-companies", "/api/insurance/companies", "insurance.read", "شركات التأمين", "Insurance companies"), post("create-insurance-company", "/api/insurance/companies", "insurance.manage", "إضافة شركة تأمين", "Create insurance company"), put("update-insurance-company", "/api/insurance/companies/{id}", "insurance.manage", "تعديل شركة تأمين", "Update insurance company"), get("insurance-plans", "/api/insurance/companies/{companyId}/plans", "insurance.read", "خطط التأمين", "Insurance plans"), post("create-insurance-plan", "/api/insurance/companies/{companyId}/plans", "insurance.manage", "إضافة خطة تأمين", "Create insurance plan"), put("update-insurance-plan", "/api/insurance/companies/{companyId}/plans/{id}", "insurance.manage", "تعديل خطة تأمين", "Update insurance plan"), get("insurance-policies", "/api/insurance/policies", "insurance.read", "وثائق التأمين", "Insurance policies"), post("create-insurance-policy", "/api/insurance/employees/{employeeId}/policies", "insurance.manage", "إضافة وثيقة تأمين", "Create insurance policy"), put("update-insurance-policy", "/api/insurance/employees/{employeeId}/policies/{id}", "insurance.manage", "تعديل وثيقة تأمين", "Update insurance policy"), patch("archive-insurance-company", "/api/insurance/companies/{id}/archive", "insurance.manage", "أرشفة شركة تأمين", "Archive insurance company"), patch("archive-insurance-plan", "/api/insurance/plans/{id}/archive", "insurance.manage", "أرشفة خطة تأمين", "Archive insurance plan"), patch("archive-insurance-policy", "/api/insurance/policies/{id}/archive", "insurance.manage", "أرشفة وثيقة تأمين", "Archive insurance policy"),
  ] },
  { id: "platform-operations", label: label("تشغيل المنصات", "Platform operations"), endpoints: [
    get("platforms", "/api/platform-operations/platforms", "platform_accounts.read", "المنصات", "Platforms"), post("create-platform", "/api/platform-operations/platforms", "platform_accounts.manage", "إضافة منصة", "Create platform"), put("update-platform", "/api/platform-operations/platforms/{id}", "platform_accounts.manage", "تعديل منصة", "Update platform"), get("contracts", "/api/platform-operations/contracts", "platform_accounts.read", "العقود", "Contracts"), post("create-contract", "/api/platform-operations/contracts", "platform_accounts.manage", "إضافة عقد", "Create contract"), put("update-contract", "/api/platform-operations/contracts/{id}", "platform_accounts.manage", "تعديل عقد", "Update contract"), get("platform-accounts", "/api/platform-operations/accounts", "platform_accounts.read", "حسابات المنصات", "Platform accounts"), post("create-platform-account", "/api/platform-operations/accounts", "platform_accounts.manage", "إضافة حساب منصة", "Create platform account"), put("update-platform-account", "/api/platform-operations/accounts/{id}", "platform_accounts.manage", "تعديل حساب منصة", "Update platform account"), get("registrations", "/api/platform-operations/registrations", "platform_accounts.read", "تسجيلات المنصة", "Platform registrations"), post("create-registration", "/api/platform-operations/registrations", "platform_accounts.manage", "إضافة تسجيل", "Create platform registration"), put("update-registration", "/api/platform-operations/registrations/{id}", "platform_accounts.manage", "تعديل تسجيل", "Update platform registration"), get("platform-assignments", "/api/platform-operations/assignments", "platform_assignments.read", "إسنادات المنصات", "Platform assignments"), post("create-platform-assignment", "/api/platform-operations/assignments", "platform_assignments.manage", "إسناد حساب منصة", "Assign platform account"), post("close-platform-assignment", "/api/platform-operations/assignments/{id}/close", "platform_assignments.manage", "إنهاء إسناد منصة", "Close platform assignment"), patch("archive-platform-resource", "/api/platform-operations/{resource}/{id}/archive", "platform_accounts.manage", "أرشفة مورد منصة", "Archive platform resource"),
  ] },
  { id: "promissory-notes", label: label("سندات التعهد", "Promissory notes"), endpoints: [
    get("promissory-notes", "/api/promissory-notes", "promissory_notes.read", "كل سندات التعهد", "All promissory notes"), post("create-promissory-note", "/api/promissory-notes/employee/{employeeId}", "promissory_notes.manage", "إضافة سند تعهد", "Create promissory note"), put("update-promissory-note", "/api/promissory-notes/employee/{employeeId}/{id}", "promissory_notes.manage", "تعديل سند تعهد", "Update promissory note"), patch("archive-promissory-note", "/api/promissory-notes/{id}/archive", "promissory_notes.manage", "أرشفة سند تعهد", "Archive promissory note"),
  ] },
  { id: "residency-and-licenses", label: label("الإقامات والرخص", "Residency and licenses"), endpoints: [
    get("residency-permits", "/api/compliance/residency-permits", "residency.read", "تصاريح الإقامة", "Residency permits"), post("create-residency", "/api/compliance/employees/{employeeId}/residency-permits", "residency.manage", "إضافة إقامة", "Create residency permit"), put("update-residency", "/api/compliance/employees/{employeeId}/residency-permits/{id}", "residency.manage", "تعديل إقامة", "Update residency permit"), get("driver-licenses", "/api/compliance/driver-licenses", "licenses.read", "رخص القيادة", "Driver licenses"), post("create-driver-license", "/api/compliance/employees/{employeeId}/driver-licenses", "licenses.manage", "إضافة رخصة قيادة", "Create driver license"), put("update-driver-license", "/api/compliance/employees/{employeeId}/driver-licenses/{id}", "licenses.manage", "تعديل رخصة قيادة", "Update driver license"), patch("archive-residency", "/api/compliance/residency-permits/{id}/archive", "residency.manage", "أرشفة إقامة", "Archive residency permit"), patch("archive-driver-license", "/api/compliance/driver-licenses/{id}/archive", "licenses.manage", "أرشفة رخصة", "Archive driver license"),
  ] },
  { id: "user-profile", label: label("ملف المستخدم", "User profile"), endpoints: [
    get("my-profile", "/api/user-profile/me", undefined, "ملفي", "My profile"), patch("update-preferences", "/api/user-profile/me/preferences", undefined, "تعديل التفضيلات", "Update preferences"), get("my-authorization", "/api/user-profile/me/authorization", undefined, "الصلاحيات الفعلية", "Effective permissions"),
  ] },
];

export function routeParameters(path: string) {
  return [...path.matchAll(/\{([^}]+)\}/g)].map((match) => match[1]);
}

export function resolvePath(path: string, values: Record<string, string>) {
  return path.replace(/\{([^}]+)\}/g, (_, parameter: string) => encodeURIComponent(values[parameter]?.trim() ?? ""));
}
