from pathlib import Path
import json,re,collections
maps=json.loads(Path('.codex-temp/manage-map.json').read_text());keys={};group=None
for line in Path('src/LogisticsERP.Application/Authorization/PermissionKeys.cs').read_text().splitlines():
 m=re.search(r'public static class (\w+)',line)
 if m:group=m[1]
 m=re.search(r'public const string (\w+) = "([^"]+)"',line)
 if m:keys[f'PermissionKeys.{group}.{m[1]}']=m[2]
changes=json.loads(Path('.codex-temp/manage-endpoint-changes.json').read_text());affected={(Path(r['file']).name,r['method']) for r in changes}
affected.update({('SupportAccessController.cs','RequestAccess'),('SupportAccessController.cs','Revoke'),('VehiclesController.cs','ChangeStatus'),('VehiclesController.cs','RecordOdometer')})
# Actual method names for dynamically authorized vehicle operations.
for f in [Path('src/LogisticsERP.Api/Controllers/VehiclesController.cs')]:
 s=f.read_text()
 for call in ['ChangeAdministrativeStatusAsync','RecordOdometerAsync']:
  pos=s.index('service.'+call);matches=list(re.finditer(r'public async Task<IActionResult> (\w+)\(',s[:pos]));affected.add((f.name,matches[-1][1]))
endpoints=[];related=[]
for file in sorted(Path('src/LogisticsERP.Api/Controllers').glob('*.cs')):
 s=file.read_text();base=re.search(r'\[Route\("([^"]+)"\)\]',s)
 if not base:continue
 for http in re.finditer(r'\[Http(Get|Post|Put|Patch|Delete)(?:\("([^"]*)"\))?\]',s):
  tail=s[http.end():];method=re.search(r'public\s+(?:async\s+)?Task<IActionResult>\s+(\w+)\s*\(',tail)
  if not method:continue
  attrs=tail[:method.start()];name=method[1]
  if re.search(r'\[Http(?:Get|Post|Put|Patch|Delete)',attrs):continue
  route=http[2] or '';route=route if route.startswith('/') else '/'+base[1].strip('/')+('/'+route if route else '')
  refs=re.findall(r'\[RequirePermission\((PermissionKeys\.\w+\.\w+)\)\]',attrs)
  req=[keys[r] for r in refs];dynamic=None
  if file.name=='VehicleDailyDistancesController.cs' and name=='UpsertManual':dynamic='fleet.daily_distances.create when no manual reading exists (including GPS-only rows); fleet.daily_distances.update when a manual reading already exists.'
  if file.name=='HrWorkflowsController.cs' and name=='TransitionAbsenceCase':dynamic='absence_cases.delete when status is Cancelled; absence_cases.update for all other transitions.'
  if file.name=='VehiclesController.cs' and 'service.ChangeAdministrativeStatusAsync' in tail[method.start():method.start()+1000]:dynamic='fleet.vehicles.decommission for decommission; fleet.vehicles.update for all other statusAction values.'
  if file.name=='VehiclesController.cs' and 'service.RecordOdometerAsync' in tail[method.start():method.start()+600]:dynamic='fleet.corrections.create when isCorrection=true; fleet.vehicles.create otherwise.'
  e=dict(controller=file.stem,action=name,method=http[1].upper(),path=route,requiredPermissions=req,permissionMode='all',conditionalPermission=dynamic)
  if (file.name,name) in affected:endpoints.append(e)
  elif any(k==m['prefix']+'.read' for k in req for m in maps.values()) or (file.name=='JahezController.cs' and http[1]=='Get'):related.append(e)
# Scope/trust metadata comes from the actual seed catalog.
seed=Path('src/LogisticsERP.Infrastructure/Persistence/SeedData/PermissionSeedCatalog.cs').read_text();families=[]
for m in maps.values():
 ref=f'PermissionKeys.{m["group"]}.{m["base"]}Create';line=next(x for x in seed.splitlines() if ref in x)
 families.append(dict(legacyKey=m['old'],read=m['prefix']+'.read',create=m['prefix']+'.create',edit=m['prefix']+'.update',delete=m['prefix']+'.delete',requiresHousingScope='housingScope: true' in line,requiresClientScope='clientScope: true' in line,isSensitive='sensitive: true' in line,isHighTrust='highTrust: true' in line))
payload=dict(version='2026-10-06',families=families,changedEndpoints=endpoints,relatedReadEndpoints=related)
Path('docs/management-permissions-endpoints.json').write_text(json.dumps(payload,indent=2,ensure_ascii=False)+'\n')
lines=['# Management permissions: frontend handoff','', 'Updated 6 October 2026. This document is authoritative for the management-permission split; older feature handoffs may still mention `.manage`.', '',f'{len(families)} former management permissions now have independent Read, Create, Edit, and Delete keys. Edit is named `.update` in API payloads. {len(endpoints)} affected endpoints are listed below with every required permission. Paths, HTTP verbs, request/response bodies, row versions, and file formats are unchanged.','', '## Frontend changes','', '- Remove checks and submitted values ending in `.manage`. Use the exact keys below; do not infer permission from the user’s role name.', '- Render four separate permission controls per family: Read (`.read`), Create (`.create`), Edit (`.update`), Delete (`.delete`). A grant for one action does not imply another.', '- Fetch the catalog from `GET /api/users/permissions` (`permissions.read`). Fetch the signed-in user’s authorization from `GET /api/user-profile/me/authorization` after login, token refresh, and access changes. Use `effectivePermissionKeys` for visibility, and retain `roles`, `directPermissions`, scope flags, `scopes`, and validity windows for resource-specific checks.', '- Multiple required permissions in an endpoint row are AND checks: all must be granted. Shared workflows still require their additional stock, work-order, approval, import, credential, or file permissions.', '- Delete buttons include archive, remove, assignment return/close, support revocation, and cancellation operations shown in the table. Preserve existing soft-delete/history behavior and confirmations.', '- Some families have no separate endpoint for an action yet. The permission is available for assignment, but does not add a new CRUD API. In particular, Jahez shared financial/history views continue to use `jahez.read`; do not replace it with a family read key unless the endpoint table says so.', '- Keep the existing client scopes and sensitive/high-trust grant rules. Housing permissions remain module-level. A globally visible action can still be refused for a resource outside the user’s scope.', '- On 403, refresh authorization and show the API Problem Details message. After the database authorization-version update, refresh tokens or ask the user to log in if the session can no longer refresh.','', '## Permission keys','', '| Previous key | Read | Create | Edit | Delete | Client scope | High trust |','|---|---|---|---|---|---|---|']
for f in families:lines.append('| '+' | '.join('`'+f[k]+'`' for k in ['legacyKey','read','create','edit','delete'])+' | '+('Yes' if f['requiresClientScope'] else 'No')+' | '+('Yes' if f['isHighTrust'] else 'No')+' |')
lines+=['','## Affected endpoints','', 'All keys in a row must be granted. For conditional rows, the service chooses the key from the request and current database state.']
for controller,es in __import__('itertools').groupby(endpoints,key=lambda e:e['controller']):
 lines+=['',f'### {controller.removesuffix("Controller")}','', '| Method | Endpoint | Required permissions |','|---|---|---|']
 for e in es:lines.append(f'| {e["method"]} | `{e["path"].replace("|","&#124;")}` | '+(' + '.join('`'+k+'`' for k in e['requiredPermissions']) if e['requiredPermissions'] else '')+(('; ' if e['requiredPermissions'] else '')+e['conditionalPermission'] if e['conditionalPermission'] else '')+' |')
lines+=['','## Related read endpoints','', 'These existing read permissions still apply to list/detail screens. These routes are included so the frontend can pair each action with its screen’s data permissions.','', '| Method | Endpoint | Required permissions |','|---|---|---|']
for e in related:lines.append(f'| {e["method"]} | `{e["path"].replace("|","&#124;")}` | '+' + '.join('`'+k+'`' for k in e['requiredPermissions'])+' |')
lines+=['','## Authorization editing payloads','', '`PUT /api/users/{userId}/permissions` requires `permissions.create`, `permissions.update`, and `permissions.delete` because it replaces the full assignment set. Send the complete desired set, not only the changed permission. Removing an entry revokes it.', '', '```json','{"assignments":[{"permissionKey":"fuel.create","effect":"Grant","startsAtUtc":null,"expiresAtUtc":null,"reason":"Create fuel cards","isAllHousingScope":false,"isAllClientScope":false,"includesFuturePlatformContracts":false,"scopes":[]}]}','```','', '`PUT /api/users/{userId}/roles` and `PUT /api/users/roles/{roleId}/permissions` require all three role action permissions. Role permission replacement keeps its existing `{ "permissionKeys": [...], "rowVersion": "..." }` body. Read permission is independently assigned; do not silently add it when saving one write permission.','', '## Database and rollout','', 'Every active legacy management role grant and direct assignment is expanded to all four keys. Direct denies, expiry/start dates, reasons, client/housing flags, and exact scopes are copied; temporary support-access permission arrays are expanded and deduplicated. Existing explicit denies still override grants. Original assignment and seeded IDs remain on Create wherever possible.', '', 'Compatibility `.manage` definitions and assignments remain in the hosted database while the older API is running. The updated backend rejects `.manage`, hides compatibility entries from permission editing responses, and uses only the new action keys. Publish the updated backend before the frontend starts sending the new permissions. Backend publication is a separate deployment step.', '', 'Application and Identity migrations are applied together through the transaction script. Rollback requires restoring the authorization backup: independently edited permissions cannot safely be collapsed back into management access.', '', 'Machine-readable files: [endpoint map](management-permissions-endpoints.json) and [TypeScript constants and endpoint guards](management-permissions.ts). Database execution and verification results are recorded in [deployment notes](management-permissions-db-update.md).']
Path('docs/management-permissions-frontend-handoff.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
ts='// Management-permission split, 2026-10-06. Generated from backend permission keys and controllers.\nexport const managementPermissions = '+json.dumps({f['legacyKey'][:-7]:{k:f[k] for k in ['read','create','edit','delete']} for f in families},indent=2)+' as const;\n\nexport const managementEndpoints = '+json.dumps(endpoints,indent=2)+' as const;\n\n// Use effectivePermissionKeys plus the resource scope from authorization; this helper only checks key membership.\nexport function hasAllPermissions(effectivePermissionKeys: readonly string[], required: readonly string[]): boolean {\n  const granted = new Set(effectivePermissionKeys);\n  return required.every(key => granted.has(key));\n}\n'
Path('docs/management-permissions.ts').write_text(ts)
print(len(families),'families;',len(endpoints),'changed endpoints;',len(related),'related read endpoints')
